# Generated by Django 4.2.6 on 2023-10-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='lastname',
            field=models.CharField(default='Miro', max_length=200),
        ),
        migrations.AddField(
            model_name='instructor',
            name='name',
            field=models.CharField(default='Jean', max_length=200),
        ),
    ]
